### ISSUE TITLE
Is your API down?

### ISSUE THREAD

**Issue by subzero911** [maximedegreve/TinyFaces#10]
I use `Dio().get('https://tinyfac.es/api/users')` and receive
`Unhandled Exception: DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Connection timed out, errno = 110, address = tinyfac.es, port = 46874`
It means timeout.

**Comment by maximedegreve** [comment]
I'm not sure what happened there, it should be back now...

**Comment by hayelom123** [comment]
i am facing the same issue.

**Comment by maximedegreve** [comment]
@hayelom123 could we get more info on the error you're seeing?
