### ISSUE TITLE
Is the API supposed to be public?

### ISSUE THREAD

**Issue by marcorivm** [maximedegreve/TinyFaces#7]
I'm trying to test the example on the website but I'm getting an error regarding cross origin requests not being enabled.
```
XMLHttpRequest cannot load https://tinyfac.es/api/users. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://s.codepen.io' is therefore not allowed access.
```

**Comment by maximedegreve** [comment]
Hi @marcorivm , yeah it should! I will start investigating this now. Stay tuned!

**Comment by maximedegreve** [comment]
@marcorivm Can you check now? I pushed a potential fix. 
http://codepen.io/anon/pen/pRaJWq

**Comment by maximedegreve** [comment]
Due to inactivity this will be closed...

**Comment by marcorivm** [comment]
Sorry, I had to opt for another API since I was in a hurry and couldn't check it later. But the codepen example looks like it's working.
