### ISSUE TITLE
Feature request: Allow hotlinking directly to the images via URLs?

### ISSUE THREAD

**Issue by EmilStenstrom** [maximedegreve/TinyFaces#8]
I'm generating about 100 people to construct a fake family tree. I'll handle all the names, and other data, but I'm missing images. I don't have any javascript on the site yet, it's a pure backend app. The easiest way to integrate this would be to via a direct URL.

Would it be possible to access only the images of tinyfac.es via URL?

The URLs seem to be https://tinyfac.es/data/avatars/344CFC24-61FB-426C-B3D1-CAD5BCBD3209-200w.jpeg

But the UUID is unique for each image, and can't be created by me I guess?

Would you be open to chaning that ID to be a simple increasing number, so I can hotlink images from my app?

**Comment by maximedegreve** [comment]
It's something I could definitely do however the project is super old right now and would need a rewrite so it might not be anytime soon I can add this. Maybe one day I will do a live YouTube cast where I port this.

**Comment by EmilStenstrom** [comment]
@maximedegreve 👍

**Comment by maximedegreve** [comment]
Hi @EmilStenstrom,

This is now available 🎉:
https://tinyfac.es/api/avatar.jpg?gender=female&quality=0

Let me know if you find any issues with this.

**Comment by EmilStenstrom** [comment]
@maximedegreve That's awesome! :)
