### ISSUE TITLE
WebSite SSL certificate just expired :(

### ISSUE THREAD

**Issue by breno12321** [maximedegreve/TinyFaces#9]
Hi, just checked that the certificate for HTTPs requests expired 😢. Just  wanted to point it out, bc I was using it for a demo and my avatars are all gone 😅

![image](https://user-images.githubusercontent.com/13908455/104844729-a1626280-58b0-11eb-9e8b-5d82e1bcb2fc.png)

**Comment by maximedegreve** [comment]
This should be fixed now.
